### ISSUE TITLE
Markíza konto

### ISSUE THREAD

**Issue by Jakubicek222** [cache-sk/plugin.video.freeview.sk#10]
yitevod357@aosod.com
heslo123
Registrované na novom scripte, je to v doplnku odskúšané, a funkčné.
Prajem príjemný deň

**Comment by cache-sk** [comment]
Uz tam nechcem davat univerzalne konto, nakolko uz to povodne zacalo blbnut (markizacka stranka sa sla zblaznit z toho ze z viacero lokacii naraz chcelo ziskat stream). Takze nech si kazdy user zaregistruje vlastne konto na 10-minutovy mail..
