### ISSUE TITLE
🤔🤔🤔 dokedy to pojde? 🤔🤔🤔

### ISSUE THREAD

**Issue by Jakubicek222** [cache-sk/plugin.video.freeview.sk#11]
dokedy to pojde?
#extinf:0 tvg-provider="ocko",Ocko black
https://bit.ly/provider-ocko-channel-ockoblack
#extinf:0 tvg-provider="saveearth",love nature 4k
https://bit.ly/provider-saveearth-channel-lovenature4k

**Comment by cache-sk** [comment]
Ako som uz pisal predtym, tento addon nieje na to aby zlieval dokopy rozne cierne retransmisie ci streamy z platenych sluzieb tretich stran, len a len streamy vysielatelov priamo z ich stranok. Netusim co je moderntv.eu ale urcite to nieje free sluzba.
