### ISSUE TITLE
Modern TV

### ISSUE THREAD

**Issue by Jakubicek222** [cache-sk/plugin.video.freeview.sk#13]
Rozmyslanie mas na urovni 0%
![image](https://user-images.githubusercontent.com/106910269/230725880-0caff121-e96f-4e79-8a5f-15dea5f31337.png)

**Comment by cache-sk** [comment]
"Služba je dostupná iba pre užívateľov určitých káblových sietí a internetových poskytovateľov."

Nechapem preco sa mam opakovat znova a znova o com je tento doplnok.
