### ISSUE TITLE
automatické nastavenie PVR IPTV Simple Client - playlist aj EPG nefunkcne

### ISSUE THREAD

**Issue by jarchiv** [cache-sk/plugin.video.freeview.sk#14]
Ahoj,

nie som si isty ci je toto spravne forum, ale skusim... :-)

k dnesnemu dnu aktualna verzia KODI, aktualne verzia Simple Client, aktualna verzia pluginu freeview.sk (doteraz som to nepouzival tak neviem odkedy je to funkcne/nefunkcne a manual som na to nenasiel nikde - mam to cca 6dni). Mam v nastaveniach zapnutu funkciu generovania EPG na kazdy den - co po zapnuti mi vypise hlasku ze je vygenerovane(tvari sa ze je to OK a proces zbehol).

result:
- sledoavnie streamov priamo v plugine OK (bez EPG , ak tam maju byt)
- ked nastavim "automaticke nastavenie Simple Client programova ponuka" - vypise hlasku ze OK, restartnem KODI, pustim Simple Client a nemam tam zoznam programov. Neviem na akom principe to ma nastavit script - predpokaldal som ze vygeneruje niekde lokalne playlist a same zapne/vytvori profil v ktorom nastavi lokalnu cestu. TOTO NEFUNGUJE. Napise vygenerovane restartni KODI - no po restarte ziadna ponuka.
- manualne vygenerovanie playlistu - toto funguje super, vygeneruje mi playlist. V Simple Client vytvorim profil kde zadam lokalnu cestu na dany playlist a pozeram. 
- ked nastavim "automaticke nastavenie Simple Client EPG" - vypise hlasku ze OK, restartnem KODI, pustim Simple Client a nemam tam zoznam programov ani EPG. Ak vygenerujem rucne playlist, rucne nastavim cestu k nemu - playlist funguje ale EPG k nemu nie. V profile neviem zadat cestu k vygenerovanemu EPG lebo neviem kam ho automaticky generuje.

zaver:
- sfunkcnit automaticke nastavenie programov pre simple client
- sfunkcnit automaticke generovanie epg pre simple client
- pridat dalsiu moznost v menu pre export rucne vygenerovaneho EPG(tak ako si rucne generujem playlist) -  a subor si ulozim lokalne do nejakeho priecinku a v simple client ked urobim rucne profil kde zadam cestu k playlistu zadam aj cestu k epg

Ak viem niekde poslat nejaky log co pomoze tak kam...

Vdaka, pekny den.

EDIT: dakujem za odpoved aj vysvetlenie a priebezny progress, moja chyba ze som necital #12 - ak je to teda duplikat moze sa vlakno zatvorit.

**Comment by cache-sk** [comment]
Duplikat #12 

Ako je tam popisane, od tej verzie su multi instancie pvr simple clienta, cize inak povedane, aj ked sa pluginu setnu spravne hodnoty, on to ignoruje z dovodu, ze hodnoty si uz nenacitava zo settings, ale z vlastnych separatnych xml suborov.

Mam rozpracovane riesenie, co zachova aj spatnu kompatibilitu pre starsie verzie.

Workaround je 
1) export playlistu niekam na dostupne miesto
2) vytvorenie si profilu v nastaveniach pvr iptv simple client (tento krok bude potrebny aj potom, nebudem vytvarat profil, len budem nastavovat cesty)
3) v profile si nastavit playlist z miesta, kam bol exportovany
4) v profile si nastavit epg z interneho data adresara - treba sa preklikat do addon_data adresaru, tam si najst plugin.video.freeview.sk a v om bude (ak uz je generovane) epg.xml)

**Comment by cache-sk** [comment]
Vyriesene v 0.8.0.
