### ISSUE TITLE
TV Nova/y

### ISSUE THREAD

**Issue by erik-praznovsky** [cache-sk/plugin.video.freeview.sk#16]
Zdravim,
asi zasa zmena v posielanych datach, vsetky TV Novy rovnaka error hlaska:
'NoneType' object has no attribute 'group'

Thx za fix, ak sa podari :)

**Comment by JSebso** [comment]
V resources/providers/nova.py
treba zmenit riadok 78   ` matches = re.search('{"tracks":{"HLS":\[{"src":"([^"]*)","lang":"cze","type":"application', content)`  trebars za `matches = re.search('{"sources":\[{"src":"([^"]*)","type":"application', content)`
Aspon mne to tak funguje

**Comment by cache-sk** [comment]
@JSebso Moze byt, mrkol som na to len cez mobil, mozno najskor koncom tyzdna sa na to pozriem, skor sa neda.

**Comment by cache-sk** [comment]
Fixed podla @JSebso
