### ISSUE TITLE
Variables.xml pre skylink

### ISSUE THREAD

**Issue by Jakubicek222** [cache-sk/plugin.video.freeview.sk#19]
Cauko, nevies mi poslat tvg-idcka skylink live tv na mail? (jakubfojtik762@gmail.com) potrebujem lebo robim novy doplnok

**Comment by cache-sk** [comment]
Cerstvy vycuc z api

https://pastebin.com/bHJzZavG

https://pastebin.com/TCxQvqsV

**Comment by sleduj-tv** [comment]
novsi vycuc na teraz nemas?

**Comment by cache-sk** [comment]
Pozrel som to a aktualne nemozem posluzit, zmenili web, maju iny login, dokonca ani konto mi uz nefunguje. Ale je pravdepodobne, ze sa tomu budem venovat, ked zaradia do live Markizu Klasik, takze to urcite bude, len nie teraz hned.
