### ISSUE TITLE
Na xbox one nefunguje verzia 5 

### ISSUE THREAD

**Issue by ParrotDevelopers** [cache-sk/plugin.video.freeview.sk#2]
Pred tou aktualizaciou som sa nimehold dostat do zozanmu a preto som pouzival m3u playlist ale teraz mi to uz ani nainstalovat nejde vzdycky to ukaze Installation Failed ani v Log-u som nic nenasiel. Mam kodi 18.9

**Comment by cache-sk** [comment]
Bohuzial, nemam ziaden xbox, takze bez nejakeho zmysluplneho logu (zapnuty debug) nic nezmozem.

**Comment by ParrotDevelopers** [comment]
Ok, posielam log z Kodi xbox-u

Keď som sa pokúšal otvoriť zoznam staníc na 4.5.0 - error 0
[https://paste.kodi.tv/tarineroho](https://paste.kodi.tv/tarineroho)

Ale stałe mi idę m3u playlist a našiel som nové m3u8 súbory pre joj

Keď sa pokúšam aktualizovať ten addon na 5.0.0

[https://paste.kodi.tv/evohusedaq](https://paste.kodi.tv/evohusedaq)

**Comment by cache-sk** [comment]
Na toto som sa zabudol pozriet, prestalo to robit?

**Comment by ParrotDevelopers** [comment]
Po aktualizácii na Kodi 19.3 a oprave chyby ktorá je na uwp verzii to išlo
