### ISSUE TITLE
nefunkcny zoznam stanic v playliste

### ISSUE THREAD

**Issue by markpastim** [cache-sk/plugin.video.freeview.sk#20]
nie je mozne spustit ziadnu stanicu, pri odkliku na Zoznam stanic vypise chybu
'NoneType' object has no attribute 'replace'

addon je nainstalovany v PC verzii Kodi Nexus 20.2

s rovnakou chybou nie je mozne ani pregenerovat EPG

**Comment by cache-sk** [comment]
opravene vo verzii 1.0.2
