### ISSUE TITLE
Prima kanale nefunguju

### ISSUE THREAD

**Issue by markpastim** [cache-sk/plugin.video.freeview.sk#22]
Chybove hlasenie:
Prehravanie zlyhalo
Zlyhalo prehravanie jedneho alebo viacerych prvkov.

Funguje iba stanica CNN Prima News

**Comment by cache-sk** [comment]
Dovod je jednoduchy, webzdarma zmazalo domenu, ktora sluzila ako proxy pre krypto data (a aj skratka na repo). Najprv od 1.1. bez varovania zaviedla limit na prenosy, teraz bez varovania rovno zmazala cely web.
Kedze je toto moj dobrovolny pocin vo volnom case, nebudem platit koli tomu hosting. Snazim sa ziskat inu nahradu, ktora bude zdarma, dovtedy budu bohuzial prima kanaly nefunkcne.

**Comment by PeterTomascik** [comment]
aky tam bol trafic? mozno nieco vymyslime.

**Comment by cache-sk** [comment]
Orientacne 2-6GB mesacne. Podarilo sa mi aktivovat "overeny" free hosting na endora.cz, ak stihnem a bude to funkcne, tak to este dnes obnovim cez nich.

**Comment by cache-sk** [comment]
No je to uz par hodin vonku, vyzera to ze to ide cez novy hosting, tak uzatvaram.
