### ISSUE TITLE
Nevidím Novu

### ISSUE THREAD

**Issue by poski1** [cache-sk/plugin.video.freeview.sk#23]
Ani v "Zoznam stanic v playliste" ani normalne v "Televize" nevidim Novu. Vidím pouze Nova Lady a jinou Novu ne.

**Comment by cache-sk** [comment]
Nova kanaly tam nie su od januara, nasadili geoblock, ktory rozoznava zatial vsetky pokusy o obidenie.

Doplnok je urceny pre slovenskeho divaka, ktory pozera z uzemia SR, cize primarne spristupnuje slovenske televizie lokalne a tie ceske, ktore sa da nejako spristupnit zo slovenskeho uzemia. Prosim nevyuzivat tento doplnok mimo uzemia SR.

Nikomu nebranim doplnok prevziat a adaptovat pre ceskeho divaka na CZ uzemi, kde je mozne pozerat ceske stanice napriamo bez kluciek.
