### ISSUE TITLE
PVR priamo v addone 

### ISSUE THREAD

**Issue by PeterTomascik** [cache-sk/plugin.video.freeview.sk#24]
Ahoj, 
Môžem malú prosbu? Šlo by do addonu priamo do Zoznam staníc v playliste integrovať PVR? Bežím na linuxe a po upgrade na kodi 21 (inštalovaný cez flatpak) mam nefunkčný iptv simple client. 
Spúšťať TV mi ide iba priamo s freeview.sk addonu. 
Toto by to vyriešilo aj do budúcna. 
dik

**Comment by cache-sk** [comment]
PVR klient je binarny addon, pokial by som mal implementovat cele PVR, tak to radsej napisem ako android appku, ako pisat c++ kod pre kazdu platformu, na ktorej kodi bezi..
To je aj zrejme dovod, preco je na danom linuxe nefunkcny iptv simple client, nezbuildovali novu verziu. Obratil by som sa na support daneho linuxu.
