### ISSUE TITLE
Stanice pridat.

### ISSUE THREAD

**Issue by sleduj-tv** [cache-sk/plugin.video.freeview.sk#26]
Tanečné súťaže TV: ORIGO LINK STREAMU: https://szts.sk/video-archiv/live-stream/
                                LINK VYTIAHNUTY ZO STREAMU: https://dash2.antik.sk/live/tanecnesutaze/index.m3u8
JOJ SVET: ORIGO LINK NA JOJ PLAY MA ANTIK
DOKTOR TV: https://live.tvdoktor.sk/high/index.m3u8 (ZNAME JE TO UZ Z LINKU)
Prosim ta posli epg idcka skylinku najnovsie

**Comment by cache-sk** [comment]
tanecne sutaze a tv doktor mozem pridat, ked budem riesit tu markizu klasik, ale ten joj svet nevidim realne, nemaju to vo free konte, neverim, ze to nemaju zabezpecene a aj tie free jednotka a dvojka co maju som uz pozeral a su kryptovane widevine, cize tam bude potrebny login a nechcelo sa mi to riesit - privela prace (v principe sa moze riesit rovno cely antik addon) a uz na to nemam tolko casu, skor to len udrzujem..

**Comment by sleduj-tv** [comment]
Ale netreba tam nic, len widevine key, ktory je lahke zohnat
Slager 1 napriklad
#EXTINF: -1 tvg-id="684-slagr-original" group-title="Hudobné", Šláger Originál
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://drm.antik.sk/widevine/key
https://dash2.antik.sk/stream/hisi_slager_original/playlist_cbcs.mpd

**Comment by cache-sk** [comment]
no to ma poser, to vyzera, ze daco nedokoncili, alebo co.. nedava zmysel nasadit drm a nerobit licencie per user.. kazdopadne by bolo lepsie spravit rovno separe antik playlist, kedze sa da takto vytiahnut uplne vsetko, vratane premiovych kanalov..

**Comment by sleduj-tv** [comment]
No, ved to. Ja to pouzivam len na nejaky antik, ostatne mam na ipcku. Staci len key a ide vsetko. A Full HD

**Comment by sleduj-tv** [comment]
kazdopadne mozes riesit klasik markizu. uz vysielaju na ich webe

**Comment by barney222** [comment]
je možné prosím rozbehať ctsport aj na území Slovenska?

**Comment by sleduj-tv** [comment]
Ano. A dokonca z ivysilani officialneho ide bez geoblocku

**Comment by barney222** [comment]
> Ano. A dokonca z ivysilani officialneho ide bez geoblocku

ako, prosím ťa?

**Comment by sleduj-tv** [comment]
pojdes na https://www.ceskatelevize.cz/ivysilani/
das zive vysilani
a kliknes na ct sport

**Comment by sleduj-tv** [comment]
![image](https://github.com/user-attachments/assets/626cfac1-d0f0-466f-ae11-e95f4cf2cc93)
frci a ako pekne

**Comment by barney222** [comment]
zjavne si nenapísal to najdôležitejšie, lebo len takto to nefunguje... 🤦

**Comment by sleduj-tv** [comment]
funguje pustis si to online 🤓

**Comment by sleduj-tv** [comment]
jak chces ct sport na slovensku tak si zaplat 30 centov. teda ak to nechces pozerat v ivysilani. ja mam tohto poskytovatela. jeho instagram: https://www.instagram.com/sledujtelku/

**Comment by barney222** [comment]
![IMG_20240714_114939](https://github.com/user-attachments/assets/2366dc17-40c4-4a41-a3b8-289c453b39cf)
ne nefunguje to cez web... zrejme mas nejakú vpnku ktoru si zabudol napísať

**Comment by sleduj-tv** [comment]
som bez vpn. ale byvam blizko hranic. mozno preto. skus obist teda drm antiku z webtv.tv a tam ct sport je

**Comment by cache-sk** [comment]
- markiza klasik pridane, zatial bez epg, skylink este nepridal do live
- prekvapivo zase ide nova cinema
- pridane aj drtv aj tance, tiez nemaju epg

co sa tyka dumpov pre @sleduj-tv - https://pastebin.com/ctVaNmZk https://pastebin.com/WguvLEfy - snad sa mi to podarilo koser

co sa tyka antiku, este sa tomu budem venovat, ale ako som pisal, nezaradim to do freeview zoznamu, ked uz tak separe vsetko co sa da, mozno tam zduplikujem aj epg so skylinku.. len ked sa to prilis rozsiri, tak to samozrejme bloknu.. toto je tenky lad..

co sa tyka ct sport a ct vseobecne, robil som prve experimenty a slo to obchadzat ciastocne podobne ako primu, ale len s widevine krytpovanymi streamami, nekryptovane mi nesli.. ked budem mat cas, budem sa tomu venovat..
