### ISSUE TITLE
Prima nefunguje 

### ISSUE THREAD

**Issue by ParrotDevelopers** [cache-sk/plugin.video.freeview.sk#3]
Všimol som si že Prima prestala fungovať

**Comment by cache-sk** [comment]
Bohuzial, nemam aktualne na to cas, ale ked sa bude dat, skusim to pozriet. Menili stranku, ostava dufat aby nemali vylepsenu detekciu ako ma uz Nova.

**Comment by ParrotDevelopers** [comment]
Detekcia vylepšená nebi VPN stále funguje a zohnal som si Direct m3u8 linky na Primu ale maju geoblock takže používám VPN alebo proxy

**Comment by cache-sk** [comment]
proxy updatnuta na nove streamy, pridane 2 nove prima kanaly
