### ISSUE TITLE
Ak by si chcel tak tu sú origo linky NASA a Nickelodeon Ukraine Pluto TV

### ISSUE THREAD

**Issue by Jakubicek222** [cache-sk/plugin.video.freeview.sk#8]
Tak tu je originál:
NASA: https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8
Nickelodeon Ukraine Pluto TV: http://siloh-sp.plutotv.net/lilo/production/NickUkraine/master.m3u8
A ak by si bol taký dobrý a mal link na Markízu Krimi a Novu International z nejakých svojich ak máš na mail: jakubfojtik762@gmail.com

**Comment by cache-sk** [comment]
Ten ukrajinsky nickolodeon urcite nie, aj ked to vyzera ze to je ich origo stream, tento plugin je pre slovenskeho divaka na slovensku..

Ten NASA stream by ma zaujimalo aky je zdroj, prezrel som cely web NASA a oni uz maju ofic stream na youtube, takze je to nejaky pozostatok predosleho? Ako dlho bude fungovat?

Novu international ani nemam a Markiza - ako som pisal, stream sa ziskava pri kazdom pustani zo stranky markizy, dynamicky, nasimuluje sa prihlasenie cez prehliadac, nema to staticku url.

**Comment by Jakubicek222** [comment]
Nie, dam ti odkaz
https://www.nasa.gov/multimedia/nasatv/index.html

**Comment by cache-sk** [comment]
Oba Nasa kanaly pridane v 0.7.0
