### ISSUE TITLE
JOJ Family,Markiza,Doma,Dajto,Krimi - Nefungujú

### ISSUE THREAD

**Issue by Csillagember** [cache-sk/plugin.video.freeview.sk#9]

**Comment by cache-sk** [comment]
JOJ Family ma expirovany certifikat na stranke (pridam tam skip, ale ono sa to asi vyriesi aj samo skor, ked daju novy certifikat), markiza kompletne zmenila stranku, cize treba cely proces ziskania streamu spravit nanovo - ked to bude, tak to bude.

**Comment by cache-sk** [comment]
fixed v 0.7.0, markiza vyzaduje vlastnu registraciu a konto (povodne sharovane uz nefunguje a aj tak robilo problemy v poslednom case)

**Comment by Csillagember** [comment]
Dakujeme ale JOJ Family nadalej nejde...

**Comment by cache-sk** [comment]
Aktualne ma totiz ta stranka, kde ide stream joj family, vypadok - hlasi chybu serveru.
